sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
git:
  depth: 9999999
before_script:
  - git fetch origin master:master
  - git fetch origin test:test
  - git pull
  - git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
script:
  - ./gradlew build --stacktrace -i
after_script:
  - find -name TEST* -exec cat {} \;
notifications:
  email: false
